[book]
title = "powerd6 Specification"
description = "The open specification for the powerd6 system and tools"
authors = ["Hector Castelli Zacharias"]

language = "en"
multilingual = false

src = "docs"

[preprocessor.toc]
command = "mdbook-toc"

renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/powerd6/specification"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/powerd6/specification/edit/master/guide/{path}"
cname = "specification.powerd6.org"

[output.linkcheck]
follow-web-links = true
traverse-parent-directories = false
user-agent = "mdbook-linkcheck-0.4.0"
cache-timeout = 43200
warning-policy = "error"
exclude = [
  'https://powerd6.org', # Currently empty and failing SSL check
]
